@baseUrl = http://localhost:3000
@baggageId=69fda8214a5f6f66e7b79db5
@userId=6a0ecbfbe4e985cc8c7ea664

### Create Baggage Data
POST {{baseUrl}}/baggages
Content-Type: application/json

{
    "name": ""
}

### Get all baggages
GET {{baseUrl}}/baggages

### Get a specific baggage
GET {{baseUrl}}/baggages/{{baggageId}}

### update a specific baggage
PATCH {{baseUrl}}/baggages/{{baggageId}}
Content-Type: application/json

{
    "name": "T Shirt",
    "completed": true
}

### Delete a specific baggage
DELETE  {{baseUrl}}/baggages/{{baggageId}}

### create a user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "Test User",
    "email": "user@test4.com",
    "password": "abcdefgh"
}

### Get all users
GET {{baseUrl}}/users
### Get specific user
GET {{baseUrl}}/users/{{userId}}
### update a user
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
    "email": "user@test6.com"
}

### Delete specific user
DELETE {{baseUrl}}/users/{{userId}}
### register a user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Test User",
    "email": "user@test.com",
    "password": "abcdefgh"
}

### login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "abcdefgh"
}